# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[highlight]
########## necessary configurations ##########
# https://github.com/hugo-fixit/FixIt/issues/43
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false

########## necessary configurations ##########
guessSyntax = true

# Goldmark is from Hugo 0.60 the default library used for Markdown
[goldmark]
[goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[goldmark.renderer]
# whether to use HTML tags directly in the document
unsafe = true

# Table Of Contents settings
[tableOfContents]
ordered = false
startLevel = 1
endLevel = 6